### ISSUE TITLE
ScoverageSensor unable to find files

### ISSUE THREAD

**Issue by dcsobral** [RadoBuransky/sonar-scoverage-plugin#12]
I'm getting this error when running `mvn sonar:sonar`:

```
[INFO] [18:00:08.079] Sensor ScoverageSensor
[INFO] [18:00:08.113] [scoverage] Statement coverage for com.richrelevance.common:db-scala-tools is 78.38
[WARN] [18:00:08.114] File not found in file system! Users/dsobral/src/common/common/db-scala-tools/src/main/scala/com/rr/db/SqlDbHelper.scala
[INFO] [18:00:08.114] Sensor ScoverageSensor (done) | time=35ms
```

That's the absolute path without the leading slash. It shows this for the module (the error happens on both modules I configured Scala):

```
[INFO] [18:00:05.011] -------------  Scan Common :: DB Scala Tools
[INFO] [18:00:05.011] Load module settings
[INFO] [18:00:05.033] Excluded sources for coverage: 
[INFO] [18:00:05.033]   file:**/generated-sources/**
[INFO] [18:00:05.039] Initializer FindbugsMavenInitializer
[INFO] [18:00:05.039] Initializer FindbugsMavenInitializer (done) | time=0ms
[INFO] [18:00:05.039] Base dir: /Users/dsobral/src/common/common/db-scala-tools
[INFO] [18:00:05.039] Working dir: /Users/dsobral/src/common/common/db-scala-tools/target/sonar
[INFO] [18:00:05.039] Source paths: pom.xml, src/main/scala
[INFO] [18:00:05.039] Test paths: src/test/scala
[INFO] [18:00:05.040] Binary dirs: target/classes
```

The maven settings I'm using are, on the project parent:

```
  <properties>
    <scala.version>${scala.full.version}</scala.version>
    <sonar.scoverage.reportPath>target/scoverage.xml</sonar.scoverage.reportPath>
  </properties>
```

On the module:

```
  <properties>
    <sonar.sources>pom.xml,src/main/scala</sonar.sources>
    <sonar.tests>src/test/scala</sonar.tests>
  </properties>
```

**Comment by dcsobral** [comment]
Oh, I'm on Sonar 5.1.

**Comment by RadoBuransky** [comment]
I'll look at it. But it would be awesome if you could create a repo on github with a project that can reproduce this issue.

**Comment by RadoBuransky** [comment]
I have built [the plugin for 5.1 version of Sonar] [https://github.com/RadoBuransky/sonar-scoverage-plugin/releases/tag/v5.1.0-SNAPSHOT]. Please try this version and let me know the result. I have tried it and "it works on my machine" for the SBT multi-module sample project.

**Comment by dcsobral** [comment]
That didn't fix it. I'll work on reproducing the problem on a small example
tomorrow.

On 28 April 2015 at 11:26, Rado Buranský <notifications@github.com> wrote:

> I have built [the plugin for 5.1 version of Sonar] [
> https://github.com/RadoBuransky/sonar-scoverage-plugin/releases/tag/v5.1.0-SNAPSHOT].
> Please try this version and let me know the result. I have tried it and "it
> works on my machine" for the SBT multi-module sample project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RadoBuransky/sonar-scoverage-plugin/issues/12#issuecomment-97143669>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by RadoBuransky** [comment]
Thanks. Also try to run analysis using sonar-runner instead of the Maven
Sonar plugin. I'll look at it again on Sunday...

**Comment by dcsobral** [comment]
Here's the repo: https://github.com/dcsobral/sonar-test

It doesn't look like I had to do anything special to get the problem to
show up.

Running with sonar-runner didn't help either.

On 29 April 2015 at 23:16, Rado Buranský <notifications@github.com> wrote:

> Thanks. Also try to run analysis using sonar-runner instead of the Maven
> Sonar plugin. I'll look at it again on Sunday...
>
> On Thu, Apr 30, 2015 at 2:37 AM, Daniel Capo Sobral <
> notifications@github.com> wrote:
>
> > That didn't fix it. I'll work on reproducing the problem on a small
> example
> > tomorrow.
> >
> > On 28 April 2015 at 11:26, Rado Buranský <notifications@github.com>
> wrote:
> >
> > > I have built [the plugin for 5.1 version of Sonar] [
> > >
> >
> https://github.com/RadoBuransky/sonar-scoverage-plugin/releases/tag/v5.1.0-SNAPSHOT
> > ].
> > > Please try this version and let me know the result. I have tried it and
> > "it
> > > works on my machine" for the SBT multi-module sample project.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/RadoBuransky/sonar-scoverage-plugin/issues/12#issuecomment-97143669
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Daniel C. Sobral
> >
> > I travel to the future all the time.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/RadoBuransky/sonar-scoverage-plugin/issues/12#issuecomment-97621398
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RadoBuransky/sonar-scoverage-plugin/issues/12#issuecomment-97664735>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by RadoBuransky** [comment]
Thanks. Try this one please: https://github.com/RadoBuransky/sonar-scoverage-plugin/releases/tag/v5.1.1-SNAPSHOT

**Comment by RadoBuransky** [comment]
... there is a mess with absolute and relative file paths. Old Scoverage had a bug where relative paths started with leading / but then it was fixed so I had to hack my hack so that it works for you but for users with older versions of Scoverage too.

**Comment by dcsobral** [comment]
Ok, no errors this time, so I assume it is working.



On 3 May 2015 at 12:27, Rado Buranský <notifications@github.com> wrote:

> ... there is a mess with absolute and relative file paths. Old Scoverage
> had a bug where relative paths started with leading / but then it was fixed
> so I had to hack my hack so that it works for you but for users with older
> versions of Scoverage too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RadoBuransky/sonar-scoverage-plugin/issues/12#issuecomment-98519832>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by RadoBuransky** [comment]
Check the coverage report in Sonar and if it seems really ok then let me know, I'll close this issue and make a release.

**Comment by dcsobral** [comment]
I did check it, it works fine, thanks!

On 4 May 2015 at 22:18, Rado Buranský <notifications@github.com> wrote:

> Check the coverage report in Sonar and if it seems really ok then let me
> know, I'll close this issue and make a release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RadoBuransky/sonar-scoverage-plugin/issues/12#issuecomment-98943482>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.
