### ISSUE TITLE
Double percent sign in Sonar

### ISSUE THREAD

**Issue by TimSoethout** [RadoBuransky/sonar-scoverage-plugin#14]
After running scoverage and running the sonar-runner, I see the following result in Sonar:
![screen shot 2015-05-06 at 09 39 55](https://cloud.githubusercontent.com/assets/593132/7489144/bdf75006-f3d3-11e4-9b2a-00ac8a2c0ffb.png)

The percentage sign is printed twice. 
Also I was wondering if the percentage should be clickable, this is not the case with me.

**Comment by RadoBuransky** [comment]
It looks strange, but this is not an issue of this plugin. The plugin only computes a metric which is basically just a number and provides it to Sonar. Presentation is fully up to Sonar. Here is the definition of the metric:
https://github.com/RadoBuransky/sonar-scoverage-plugin/blob/master/plugin/src/main/scala/com/buransky/plugins/scoverage/measure/ScalaMetrics.scala

**Comment by TimSoethout** [comment]
I am using SonarQube 5.1. 
The display is not a real issue, but it seems the whole presentation seems different from the screenshots in the readme.
I will try the test-module provided in combination with our SonarQube.

**Comment by RadoBuransky** [comment]
That's true, the screenshots are old. Feel free to fork this repo and add new screenshots to the `sonar51` barnch.
https://github.com/RadoBuransky/sonar-scoverage-plugin/tree/sonar51
