### ISSUE TITLE
Duplicate measure in sonar

### ISSUE THREAD

**Issue by TimSoethout** [RadoBuransky/sonar-scoverage-plugin#16]
I added a sample application to my fork which I will pull request as soon as it works. ;)
https://github.com/TimSoethout/sonar-scoverage-plugin/tree/master/samples/maven/combined-scala-java-sonar

My project uses maven and I have mixed java/scala source code. I used Jacoco for the scala code coverage.

The following error occurs when running `mvn clean compile package scoverage:report sonar:sonar -X -e`:

   [ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar (default-cli) on project combined-scala-java-sonar: Can not add the same measure twice on org.sonar.api.resources.File@5b00516[key=src/main/scala/module1/HelloScala.scala,path=src/main/scala/module1/HelloScala.scala,filename=HelloScala.scala,language=Scala]: org.sonar.api.measures.Measure@85d8fe2[metricKey=statements,metric=Metric[id=<null>,key=statements,description=Number of statements,type=INT,direction=-1,domain=Size,name=Statements,qualitative=false,userManaged=false,enabled=true,origin=JAV,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=false,deleteHistoricalData=false],value=2.0,data=<null>,description=<null>,alertStatus=<null>,alertText=<null>,tendency=<null>,date=<null>,variation1=<null>,variation2=<null>,variation3=<null>,variation4=<null>,variation5=<null>,url=<null>,characteristic=<null>,requirement=<null>,personId=<null>,persistenceMode=FULL,fromCore=false]

I feel this has something to do with the code coverage being reported by both Jacoco and Scoverage. Do you have a clue?
I will try to look at it further.

**Comment by RadoBuransky** [comment]
Take a look into directory where Sonar plugins are installed to check if you don't have to Scoverage plugin twice there.

**Comment by TimSoethout** [comment]
Thanks for the tip, unfortunately not:
```
-rw-r--r-- 1 root root     9205 Mar  6 00:35 sonar-branding-plugin-1.0.jar
-rw-r--r-- 1 root root  2404852 Apr 28 10:33 sonar-checkstyle-plugin-2.3.jar
-rw-r--r-- 1 root root    17902 Apr 28 15:32 sonar-clirr-plugin-1.2.jar
-rw-r--r-- 1 root root    10325 Apr 28 15:32 sonar-cobertura-plugin-1.6.3.jar
-rw-r--r-- 1 root root  6933746 Apr 28 10:34 sonar-findbugs-plugin-3.2.jar
-rw-r--r-- 1 root root    24910 Apr 28 15:32 sonar-generic-coverage-plugin-1.1.jar
-rw-r--r-- 1 root root  2507184 Apr 28 10:34 sonar-java-plugin-3.1.jar
-rw-r--r-- 1 root root  1864762 Mar  6 00:35 sonar-jira-plugin-1.2.jar
-rw-r--r-- 1 root root  3568440 Mar  6 00:34 sonar-pmd-plugin-2.3.jar
-rw-r--r-- 1 root root 23768997 Apr 29 11:36 sonar-scala-plugin-1.1.3-SNAPSHOT.jar
-rw-r--r-- 1 root root  8953979 Jul 17  2014 sonar-scalastyle-plugin-0.0.1-SNAPSHOT.jar
-rw-r--r-- 1 root root  2680676 Apr 28 15:20 sonar-scm-git-plugin-1.0.jar
-rw-r--r-- 1 root root  5667317 May  3 18:44 sonar-scoverage-plugin-5.1.1-SNAPSHOT.jar
-rw-r--r-- 1 root root   937954 Apr 28 10:33 sonar-sonargraph-plugin-3.4.2.jar
```

**Comment by RadoBuransky** [comment]
Yes, my feeling is that it may be caused by having Java and Scala in the project even though i should work. Try to disable Java in the project and let's see if it help. I'll try to reproduce the issue too.

**Comment by TimSoethout** [comment]
Indeed. Unfortunately I do not have time now, I'll try that tomorrow. Thanks for the help already.

**Comment by TimSoethout** [comment]
Disabling Jacoco coverage does not help. It seems to be related to the multi module project; trying to confirm this now.

**Comment by TimSoethout** [comment]
Nope, single module project results in the same exception. Only thing now is the combined java/scala project... (or maybe my sonar database is corrupted due to all the testing)

**Comment by TimSoethout** [comment]
This line seems to be the problem:
https://github.com/TimSoethout/sonar-scoverage-plugin/blob/Issue12/plugin/src/main/scala/com/buransky/plugins/scoverage/sensor/ScoverageSensor.scala#L181

I wrapped it in a try/catch and it seems to almost solve my problem. I do not know what other consequences this has.

Unfortunately for my project (scala/java/maven/multi-module) this does not work entirely, since the coverage information in sonar for both scala/java only works when running `mvn scoverage:report sonar:sonar`, but not when running `mvn scoverage:report package sonar:sonar`.
I'm trying to find out what is happening. Somehow the extra `package` command breaks the scoverage reporting for sonar.

**Comment by RadoBuransky** [comment]
I have just created brand new releases for Sonar version 5.1, 4.5 and 4.2. Please try the one for your Sonar and let me know.

**Comment by TimSoethout** [comment]
Thanks Rado, this seems to result in the same result as my fix (with the try/catch). So I guess my initial problem is solved.

My second problem  (around the `mvn scoverage:report (package) sonar:sonar` seems to still exists, but I'm not sure if this is the plugin. I'll look into this some more, and open a new issue if needed.

I'll also make a pull request for the maven module in the samples project.

**Comment by RadoBuransky** [comment]
I am very happy to hear that. Thanks
