### ISSUE TITLE
Caused by: com.buransky.plugins.scoverage.ScoverageException: Current file path not set!

### ISSUE THREAD

**Issue by gurmeetsaran** [RadoBuransky/sonar-scoverage-plugin#20]
I am seeing this error when running sonar runner

22:45:09.025 INFO  - Sensor VersionEventsSensor
22:45:09.036 INFO  - Sensor VersionEventsSensor (done) | time=11ms
22:45:09.037 INFO  - Sensor com.ncredinburgh.sonar.scalastyle.ScalastyleSensor@ba5a8da
22:45:10.217 INFO  - Sensor com.ncredinburgh.sonar.scalastyle.ScalastyleSensor@ba5a8da (done) | time=1179ms
22:45:10.217 INFO  - Sensor ScoverageSensor
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 15.929s
Final Memory: 27M/725M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: com.buransky.plugins.scoverage.ScoverageException: Current file path not set!
ERROR: Caused by: Current file path not set!
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
MTVL123089eefa8:clink gsaran$

**Comment by RadoBuransky** [comment]
Hi. What version of the plugin and Sonar do you have?

**Comment by gurmeetsaran** [comment]
Sonar - 5.1
plugin - sonar-scoverage-plugin-5.1.1.jar

**Comment by RadoBuransky** [comment]
Sorry, and version of Scoverage itself? The latest 1.1.0? It looks like weird XML coverage report file. Perhaps you could publish it somewhere so I can check it.

**Comment by gurmeetsaran** [comment]
scoverage version is 1.0.4. I could not find latest 1.1.0 in the maven central. 
you can find the xml file here https://dl.dropboxusercontent.com/u/77915265/scoverage.coverage.xml

**Comment by RadoBuransky** [comment]
That's not the correct XML. Try to find a file named `scoverage.xml` and update your `sonar-project.properties` file to use it. It should be in `scoverage-report` directory.

**Comment by gurmeetsaran** [comment]
thanks a lot @RadoBuransky . It is working fine now.

**Comment by RadoBuransky** [comment]
My pleasure. Thanks

**Comment by teeschke** [comment]
Hello. 
I am using Sonar 4.5.4 and get the same error message. 
The report is located here: build/scoverage/scoverage.coverage.xml file
Gradle is configured with the following dependencies: org.scoverage:gradle-scoverage:1.0.9, org.scoverage:scalac-scoverage-plugin_2.10:1.1.1 and org.scoverage:scalac-scoverage-runtime_2.10:1.1.1
Sonar uses the sonar-scoverage-plugin-4.5.0.jar

Thanks for any hint!

**Comment by teeschke** [comment]
Okay I got it. After running reportScoverage instead of testScoverage the build/reports/scoverage/scoverage.xml file was created as expected.
Thanks!
