### ISSUE TITLE
Sonar issue

### ISSUE THREAD

**Issue by LakshmikanthS** [RadoBuransky/sonar-scoverage-plugin#9]
hi someone pls help me to resolve this issue..I am using sonar 4.3.3 and 2.2I am getting below error

Detection of duplications for [relative=src/com/citi/msm/mis/config/ObjectFactory.java, abs=C:/MSM_JAPAN_CARDS_WORKSPACE_2nd Jan 2015/MSM_Japan/src/com/citi/msm/mis/config/ObjectFactory.java]
[sonar:sonar] 18:41:21.857 DEBUG - Detection of duplications for [relative=src/com/citi/msm/mis/config/impl/JAXBVersion.java, abs=C:/MSM_JAPAN_CARDS_WORKSPACE_2nd Jan 2015/MSM_Japan/src/com/citi/msm/mis/config/impl/JAXBVersion.java]
[sonar:sonar] 18:41:21.857 DEBUG - Detection of duplications for [relative=src/com/citi/msm/mis/config/impl/MISAccountDetailsLogRecordImpl.java, abs=C:/MSM_JAPAN_CARDS_WORKSPACE_2nd Jan 2015/MSM_Japan/src/com/citi/msm/mis/config/impl/MISAccountDetailsLogRecordImpl.java]
[sonar:sonar] 18:41:21.866 DEBUG - Detection of duplications for [relative=src/com/citi/msm/mis/config/impl/MISAccountDetailsLogRecordTypeImpl.java, abs=C:/MSM_JAPAN_CARDS_WORKSPACE_2nd Jan 2015/MSM_Japan/src/com/citi/msm/mis/config/impl/MISAccountDetailsLogRecordTypeImpl.java]
[sonar:sonar] 18:41:26.613 DEBUG - Updating semaphore batch-Citi:MSM_Japan
[sonar:sonar] 18:41:31.356 DEBUG - Release semaphore on project : org.sonar.api.resources.Project@393167[id=353,key=Citi:MSM_Japan,qualifier=TRK], with key batch-Citi:MSM_Japan

BUILD FAILED
C:\MSM_JAPAN_CARDS_WORKSPACE_2nd Jan 2015\MSM_Japan\build_sonar-jshint.xml:54: org.sonar.runner.impl.RunnerException: Unable to execute Sonar

Total time: 2 minutes 29 seconds

Access Log:

127.0.0.1 - - [05/01/2015:18:38:27 +0530] "GET /sonar/batch_bootstrap/index HTTP/1.1" 200 3451 "-" "Ant/2.2"
127.0.0.1 - - [05/01/2015:18:38:28 +0530] "GET /sonar/batch_bootstrap/properties?dryRun=false HTTP/1.1" 200 251 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:38:28 +0530] "GET /sonar/deploy/plugins/index.txt HTTP/1.1" 200 1138 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:38:28 +0530] "GET /sonar/deploy/jdbc-driver.txt HTTP/1.1" 200 47 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:38:29 +0530] "GET /sonar/api/server HTTP/1.1" 200 55 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:38:31 +0530] "GET /sonar/batch_bootstrap/properties?project=CITI:WebPoc_Test&amp;dryRun=false HTTP/1.1" 200 251 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:38:31 +0530] "GET /sonar/batch_bootstrap/properties?project=CITI:WebPoc_Test&amp;dryRun=false HTTP/1.1" 200 251 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:02 +0530] "GET /sonar/api/server/version HTTP/1.1" 200 5 "-" "Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:02 +0530] "GET /sonar/batch_bootstrap/index HTTP/1.1" 200 3451 "-" "Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:02 +0530] "GET /sonar/batch_bootstrap/properties?dryRun=false HTTP/1.1" 200 251 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:02 +0530] "GET /sonar/deploy/plugins/index.txt HTTP/1.1" 200 1138 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:03 +0530] "GET /sonar/deploy/jdbc-driver.txt HTTP/1.1" 200 47 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:04 +0530] "GET /sonar/api/server HTTP/1.1" 200 55 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:06 +0530] "GET /sonar/batch_bootstrap/properties?project=Citi:MSM_Japan&amp;dryRun=false HTTP/1.1" 200 251 "-" "Sonar Ant/2.2"
127.0.0.1 - - [05/01/2015:18:39:06 +0530] "GET /sonar/batch_bootstrap/properties?project=Citi:MSM_Japan&amp;dryRun=false HTTP/1.1" 200 251 "-" "Sonar Ant/2.2"

**Comment by RadoBuransky** [comment]
Hi. Why do you think that this error is related to this Scoverage plugin?

**Comment by LakshmikanthS** [comment]
Actually I dont know what causes this error...i am very new to sonal..can u pls suggest the possible solution

**Comment by RadoBuransky** [comment]
I don't see any ERROR message in the log, check Sonar logs and probably post your issue on stackoverflow. I will close this issue.
